upstream fastcgi_backend {
    server application:9000;
}

server {
    listen 80;
    server_name localhost;

    set $MAGE_ROOT /var/www/html/;
    set $MAGE_MODE developer;

    root $MAGE_ROOT/pub;
    index index.php;

    location / {
        try_files $uri $uri/ /index.php$is_args$args;
    }

    location /pub/ {
        alias $MAGE_ROOT/pub/;
        add_header X-Frame-Options "SAMEORIGIN";
    }

    location ^~ /static/ {
        rewrite ^/static/version\d+/(.*)$ /static/$1 last;
        alias $MAGE_ROOT/pub/static/;
        expires max;
        add_header Cache-Control "public";
        add_header X-Frame-Options "SAMEORIGIN";
    }

    location ^~ /media/ {
        alias $MAGE_ROOT/pub/media/;
        expires max;
        add_header Cache-Control "public";
        add_header X-Frame-Options "SAMEORIGIN";
    }

    location ~ ^/weightloss/(.*\.php)$ {
        try_files $uri =404;
        fastcgi_pass application:9000;
        fastcgi_buffers 16 16k;
        fastcgi_buffer_size 32k;
        fastcgi_read_timeout 1800;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $realpath_root/index.php;
        fastcgi_param MAGE_RUN_CODE weightloss;
        fastcgi_param MAGE_RUN_TYPE store;
    }

    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_pass application:9000;
        fastcgi_buffers 16 16k;
        fastcgi_buffer_size 32k;
        fastcgi_read_timeout 1800;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_param MAGE_RUN_CODE demo01;
        fastcgi_param MAGE_RUN_TYPE store;
    }

    location ~* \.(ico|jpg|jpeg|png|gif|svg|css|js|woff2?)$ {
        expires max;
        log_not_found off;
        access_log off;
    }

    location ~ /(app|var|vendor|setup|update|dev|lib)/ {
        deny all;
    }
}